/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salmans;

import java.awt.List;
import java.util.ArrayList;
import java.util.EmptyStackException;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.PriorityQueue;
import java.util.Queue;
import java.util.Scanner;
import java.util.Stack;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Miguel A. Ardon E
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        grafo.addNodos(1);
        grafo.setNombreNodo(0, "Salmans");
        grafo.setPesoArista(0, 20);
        //grafo.crearRedNodos(5, 5, true, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ingrediente = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        cantidad = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        ingrediente_cb = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        eliminar = new javax.swing.JSpinner();
        jButton8 = new javax.swing.JButton();
        Producto = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        nombre_produc = new javax.swing.JTextField();
        lista_ingre = new javax.swing.JComboBox();
        tiempo = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        precio = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        mod_listaingre = new javax.swing.JComboBox();
        mod_cocina = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        mod_precio = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        producto = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        eli_produ = new javax.swing.JComboBox();
        jButton13 = new javax.swing.JButton();
        Cocina = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        orde_producto = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        cocina1 = new javax.swing.JProgressBar();
        jLabel32 = new javax.swing.JLabel();
        c2 = new javax.swing.JCheckBox();
        cocina2 = new javax.swing.JProgressBar();
        jLabel33 = new javax.swing.JLabel();
        c3 = new javax.swing.JCheckBox();
        cocina3 = new javax.swing.JProgressBar();
        jLabel34 = new javax.swing.JLabel();
        c4 = new javax.swing.JCheckBox();
        cocina4 = new javax.swing.JProgressBar();
        jLabel35 = new javax.swing.JLabel();
        c5 = new javax.swing.JCheckBox();
        cocina5 = new javax.swing.JProgressBar();
        Camiones = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        Envios = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        inicio = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        end = new javax.swing.JComboBox();
        Rutas = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ruta = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        Reporte = new javax.swing.JFrame();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_reporte = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/salmans.jpg"))); // NOI18N

        jLabel1.setText("Nombre:");

        jLabel9.setText("Cantidad:");

        jButton7.setText("Agregar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        cantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel10.setText("Nombre:");

        ingrediente_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingrediente_cbActionPerformed(evt);
            }
        });

        jLabel11.setText("Eliminar:");

        eliminar.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jButton8.setText("Eliminar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IngredienteLayout = new javax.swing.GroupLayout(Ingrediente.getContentPane());
        Ingrediente.getContentPane().setLayout(IngredienteLayout);
        IngredienteLayout.setHorizontalGroup(
            IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngredienteLayout.createSequentialGroup()
                .addGroup(IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngredienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IngredienteLayout.createSequentialGroup()
                        .addGroup(IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IngredienteLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(IngredienteLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cantidad))
                                    .addGroup(IngredienteLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(IngredienteLayout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jButton7)))
                        .addGroup(IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IngredienteLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(IngredienteLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(ingrediente_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(IngredienteLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(eliminar))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IngredienteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8)
                                .addGap(48, 48, 48)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        IngredienteLayout.setVerticalGroup(
            IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngredienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(ingrediente_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(49, 49, 49))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/salmans.jpg"))); // NOI18N

        jLabel12.setText("Agregar Producto");

        jLabel13.setText("Nombre:");

        jLabel14.setText("Lista de Ingredientes:");

        jLabel15.setText("Tiempo Cocina:");

        jLabel16.setText("Precio:");

        jButton9.setText("Agregar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        tiempo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(60), Integer.valueOf(60), null, Integer.valueOf(10)));

        jLabel17.setText("s");

        precio.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(10), null, Integer.valueOf(1)));

        jLabel18.setText("$");

        jLabel19.setText("Lista de Ingredientes:");

        jLabel20.setText("Tiempo Cocina:");

        jLabel21.setText("Precio:");

        jButton10.setText("Modificar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        mod_cocina.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(60), Integer.valueOf(60), null, Integer.valueOf(10)));

        jLabel22.setText("s");

        mod_precio.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(10), null, Integer.valueOf(1)));

        jLabel23.setText("Modificar Producto");

        jLabel24.setText("$");

        jLabel25.setText("Nombre:");

        jButton11.setText("Agregar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Agregar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel26.setText("Eliminar Producto");

        jLabel27.setText("Producto:");

        jButton13.setText("Eliminar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductoLayout = new javax.swing.GroupLayout(Producto.getContentPane());
        Producto.getContentPane().setLayout(ProductoLayout);
        ProductoLayout.setHorizontalGroup(
            ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoLayout.createSequentialGroup()
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ProductoLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabel23))
                                    .addComponent(jLabel25))
                                .addGap(125, 125, 125))
                            .addGroup(ProductoLayout.createSequentialGroup()
                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jButton9))
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProductoLayout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(71, 71, 71)
                                                .addComponent(nombre_produc, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProductoLayout.createSequentialGroup()
                                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel16))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lista_ingre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(ProductoLayout.createSequentialGroup()
                                                        .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel17))
                                                    .addGroup(ProductoLayout.createSequentialGroup()
                                                        .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel18)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jButton11)
                                            .addComponent(eli_produ, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(mod_listaingre, 0, 173, Short.MAX_VALUE)
                                            .addGroup(ProductoLayout.createSequentialGroup()
                                                .addComponent(mod_cocina, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel22))
                                            .addGroup(ProductoLayout.createSequentialGroup()
                                                .addComponent(mod_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel24))
                                            .addComponent(producto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jButton10))))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12))
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel27))
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jButton13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProductoLayout.setVerticalGroup(
            ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ProductoLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel13))
                        .addGroup(ProductoLayout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(18, 18, 18)
                            .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(nombre_produc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lista_ingre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11))
                        .addGap(21, 21, 21)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)))
                        .addGap(21, 21, 21)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)))
                        .addGap(35, 35, 35)
                        .addComponent(jButton9))
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(mod_listaingre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12))
                        .addGap(21, 21, 21)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mod_cocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22)))
                        .addGap(21, 21, 21)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mod_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24)))
                        .addGap(35, 35, 35)
                        .addComponent(jButton10)))
                .addGap(17, 17, 17)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(eli_produ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton13)
                .addGap(67, 67, 67))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/salmans.jpg"))); // NOI18N

        jLabel28.setText("Orden");

        jLabel29.setText("Producto:");

        jButton14.setText("En espera");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel30.setText("Cocineros");

        jLabel31.setText("Cocinero#1");

        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        jLabel32.setText("Cocinero#2");

        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        jLabel33.setText("Cocinero#3");

        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        jLabel34.setText("Cocinero#4");

        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        jLabel35.setText("Cocinero#5");

        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CocinaLayout = new javax.swing.GroupLayout(Cocina.getContentPane());
        Cocina.getContentPane().setLayout(CocinaLayout);
        CocinaLayout.setHorizontalGroup(
            CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CocinaLayout.createSequentialGroup()
                .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CocinaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(CocinaLayout.createSequentialGroup()
                            .addComponent(c5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel35)
                            .addGap(18, 18, 18)
                            .addComponent(cocina5, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CocinaLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jButton14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(c4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel34)
                                .addGap(18, 18, 18)
                                .addComponent(cocina4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CocinaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CocinaLayout.createSequentialGroup()
                                        .addComponent(c3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel33)
                                        .addGap(18, 18, 18)
                                        .addComponent(cocina3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CocinaLayout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(44, 44, 44)
                                        .addComponent(orde_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99)
                                        .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(CocinaLayout.createSequentialGroup()
                                                .addComponent(c2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel32)
                                                .addGap(18, 18, 18)
                                                .addComponent(cocina2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(CocinaLayout.createSequentialGroup()
                                                .addComponent(c1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cocina1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(CocinaLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(231, 231, 231))
        );
        CocinaLayout.setVerticalGroup(
            CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CocinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CocinaLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18)
                        .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orde_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31)
                            .addComponent(c1)))
                    .addComponent(cocina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(c2))
                    .addComponent(cocina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(c3))
                    .addComponent(cocina3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton14)
                    .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(c4))
                    .addComponent(cocina4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(c5))
                    .addComponent(cocina5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/salmans.jpg"))); // NOI18N

        jButton15.setText("Cargar a Camion");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CamionesLayout = new javax.swing.GroupLayout(Camiones.getContentPane());
        Camiones.getContentPane().setLayout(CamionesLayout);
        CamionesLayout.setHorizontalGroup(
            CamionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CamionesLayout.createSequentialGroup()
                .addGroup(CamionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CamionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CamionesLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jButton15)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        CamionesLayout.setVerticalGroup(
            CamionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CamionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jButton15)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/salmans.jpg"))); // NOI18N

        jButton18.setText("Mostrar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jLabel39.setText("De:");

        jLabel40.setText("A");

        javax.swing.GroupLayout EnviosLayout = new javax.swing.GroupLayout(Envios.getContentPane());
        Envios.getContentPane().setLayout(EnviosLayout);
        EnviosLayout.setHorizontalGroup(
            EnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnviosLayout.createSequentialGroup()
                .addGroup(EnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnviosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EnviosLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel39)
                        .addGap(42, 42, 42)
                        .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel40)
                        .addGap(105, 105, 105)
                        .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EnviosLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jButton18)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        EnviosLayout.setVerticalGroup(
            EnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnviosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(EnviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jButton18)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/salmans.jpg"))); // NOI18N

        jLabel37.setText("Ruta:");

        jButton17.setText("Agregar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel38.setText("Distancia:");

        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RutasLayout = new javax.swing.GroupLayout(Rutas.getContentPane());
        Rutas.getContentPane().setLayout(RutasLayout);
        RutasLayout.setHorizontalGroup(
            RutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RutasLayout.createSequentialGroup()
                .addGroup(RutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RutasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RutasLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(RutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RutasLayout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jButton17))
                            .addGroup(RutasLayout.createSequentialGroup()
                                .addGroup(RutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel37))
                                .addGap(18, 18, 18)
                                .addGroup(RutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ruta)
                                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        RutasLayout.setVerticalGroup(
            RutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RutasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(RutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(RutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jButton17)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/salmans.jpg"))); // NOI18N

        txt_reporte.setEditable(false);
        txt_reporte.setColumns(20);
        txt_reporte.setRows(5);
        jScrollPane1.setViewportView(txt_reporte);

        javax.swing.GroupLayout ReporteLayout = new javax.swing.GroupLayout(Reporte.getContentPane());
        Reporte.getContentPane().setLayout(ReporteLayout);
        ReporteLayout.setHorizontalGroup(
            ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        ReporteLayout.setVerticalGroup(
            ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salman´s");
        setBackground(new java.awt.Color(204, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/salmans.jpg"))); // NOI18N

        jButton1.setText("Ingredientes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Producto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Orden/Cocina");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Camiones");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Envios");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Rutas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton16.setText("Reporte");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Ingrediente.setTitle("Ingredientes");
        Ingrediente.setVisible(true);
        Ingrediente.pack();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Producto.setTitle("Producto");
        Producto.setVisible(true);
        Producto.pack();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Cocina.setTitle("Orden/Cocina");
        Cocina.setVisible(true);
        Cocina.pack();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Camiones.setTitle("Camiones");
        Camiones.setVisible(true);
        Camiones.pack();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Envios.setTitle("Envios");
        Envios.setVisible(true);
        Envios.pack();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Rutas.setTitle("Rutas");
        Rutas.setVisible(true);
        Rutas.pack();


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int num;
        if (bodega_ingrediente.isEmpty()) {
            bodega_ingrediente.add(new Stack<String>());
            bodega_reporte.add(new Stack<String>());
        }
        for (int i = 0; i < bodega_ingrediente.size(); i++) {
            if (!bodega_ingrediente.get(i).empty() && bodega_ingrediente.get(i).peek().contentEquals(nombre.getText())) {
                System.out.println("entro");
                num = Integer.parseInt(cantidad.getValue().toString());
                System.out.println(num);
                for (int j = 0; j < num - 1; j++) {
                    bodega_ingrediente.get(i).push(nombre.getText());
                    bodega_reporte.get(i).push(nombre.getText());
                }
                break;
            } else if (bodega_ingrediente.get(i).empty()) {
                bodega_ingrediente.add(new Stack<String>());
                bodega_reporte.add(new Stack<String>());
                System.out.println("entro2");
                bodega_ingrediente.get(i).push(nombre.getText());
                bodega_reporte.get(i).push(nombre.getText());
                num = Integer.parseInt(cantidad.getValue().toString());
                System.out.println(num);
                for (int j = 0; j < num - 1; j++) {
                    bodega_ingrediente.get(i).push(nombre.getText());
                    bodega_reporte.get(i).push(nombre.getText());
                }
                break;
            }
        }
        System.out.println(bodega_ingrediente);

        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        SpinnerNumberModel smodel = new SpinnerNumberModel();
        for (int i = 0; i < bodega_ingrediente.size() - 1; i++) {
            modelo.addElement(bodega_ingrediente.get(i).firstElement());
            smodel.setValue(bodega_ingrediente.get(i).size());
        }
        ingrediente_cb.setModel(modelo);
        lista_ingre.setModel(modelo);
        mod_listaingre.setModel(modelo);
        eliminar.setModel(smodel);
        nombre.setText("");
        cantidad.setValue(1);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int resta = 0;
        int original = 0;
        int eliminado = 0;
        original = (bodega_ingrediente.get(ingrediente_cb.getSelectedIndex()).size());
        eliminado = Integer.parseInt(eliminar.getValue().toString());
        resta = original - eliminado;
        if (resta <= 0) {
            bodega_ingrediente.get(ingrediente_cb.getSelectedIndex()).removeAllElements();
            bodega_reporte.get(ingrediente_cb.getSelectedIndex()).removeAllElements();
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            SpinnerNumberModel smodel = new SpinnerNumberModel();
            for (int i = 0; i < bodega_ingrediente.size(); i++) {
                if (!bodega_ingrediente.get(i).empty()) {
                    modelo.addElement(bodega_ingrediente.get(i).firstElement());
                    smodel.setValue(bodega_ingrediente.get(i).size());
                }
            }
            ingrediente_cb.setModel(modelo);
            eliminar.setModel(smodel);
        } else if (resta > 0) {
            for (int i = 0; i < eliminado; i++) {
                bodega_ingrediente.get(ingrediente_cb.getSelectedIndex()).pop();
                bodega_reporte.get(ingrediente_cb.getSelectedIndex()).pop();
                DefaultComboBoxModel modelo = new DefaultComboBoxModel();
                SpinnerNumberModel smodel = new SpinnerNumberModel();
                for (int j = 0; j < bodega_ingrediente.size(); j++) {
                    if (!bodega_ingrediente.get(j).empty()) {
                        modelo.addElement(bodega_ingrediente.get(j).firstElement());
                        smodel.setValue(bodega_ingrediente.get(j).size());
                    }
                }
                ingrediente_cb.setModel(modelo);
                eliminar.setModel(smodel);
            }
        }
        System.out.println(resta);
        System.out.println(bodega_ingrediente);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void ingrediente_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingrediente_cbActionPerformed
        // TODO add your handling code here:
        SpinnerNumberModel smodel = new SpinnerNumberModel();
        for (int i = 0; i < bodega_ingrediente.size() - 1; i++) {
            smodel.setValue(bodega_ingrediente.get(ingrediente_cb.getSelectedIndex()).size());
        }
        eliminar.setModel(smodel);
    }//GEN-LAST:event_ingrediente_cbActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        temp.add(bodega_ingrediente.get(lista_ingre.getSelectedIndex()).firstElement());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int time = Integer.parseInt(tiempo.getValue().toString());
        double price = Double.parseDouble(precio.getValue().toString());
        productos.add(new Producto(time, nombre_produc.getText(), price, temp));
        nombre_produc.setText("");
        temp = new ArrayList();
        tiempo.setValue(60);
        precio.setValue(10);
        System.out.println(productos);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < productos.size(); i++) {
            model.addElement(((Producto) productos.get(i)).getNombre());
        }
        producto.setModel(model);
        orde_producto.setModel(model);
        eli_produ.setModel(model);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        int confirmation = JOptionPane.showConfirmDialog(null, "Desea Eliminar esa Orden???", "Eliminar", JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION) {
            productos.remove(eli_produ.getSelectedIndex());
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < productos.size(); i++) {
            model.addElement((productos.get(i)).getNombre());
        }
        producto.setModel(model);
        orde_producto.setModel(model);
        eli_produ.setModel(model);
        System.out.println(productos);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        temp.add(bodega_ingrediente.get(lista_ingre.getSelectedIndex()).firstElement());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        productos.get(producto.getSelectedIndex()).setLista_ingrediente(temp);
        productos.get(producto.getSelectedIndex()).setPrecio(Double.parseDouble(mod_precio.getValue().toString()));
        productos.get(producto.getSelectedIndex()).setTiempo(Integer.parseInt(mod_cocina.getValue().toString()));
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        orden.offer(productos.get(orde_producto.getSelectedIndex()));
        ventas.add(productos.get(orde_producto.getSelectedIndex()));
        System.out.println(orden + "ordenes");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        if (orden.isEmpty() == false) {
            for (int i = 0; i < bodega_ingrediente.size() - 1; i++) {
                for (int j = 0; j < orden.peek().getLista_ingrediente().size(); j++) {
                    if (orden.peek().getLista_ingrediente().get(j).contentEquals(bodega_ingrediente.get(i).peek())) {
                        try {
                            bodega_ingrediente.get(i).pop();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, "No hay suficientes ingredintes en bodega!!!!");
                        }
                    }
                }
            }
            new Thread(new Hilo(orden.poll(), bodega_ingrediente, cocina1)).start();
        } else {
            JOptionPane.showMessageDialog(null, "No hay ni una orden");
        }
        c1.setSelected(false);
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
        if (orden.isEmpty() == false) {
            for (int i = 0; i < bodega_ingrediente.size() - 1; i++) {
                for (int j = 0; j < orden.peek().getLista_ingrediente().size(); j++) {
                    if (orden.peek().getLista_ingrediente().get(j).contentEquals(bodega_ingrediente.get(i).peek())) {
                        try {
                            bodega_ingrediente.get(i).pop();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, "No hay suficientes ingredintes en bodega!!!!");
                        }
                    }
                }
            }
            new Thread(new Hilo(orden.poll(), bodega_ingrediente, cocina2)).start();
        } else {
            JOptionPane.showMessageDialog(null, "No hay ni una orden");
        }
        c2.setSelected(false);
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
        if (orden.isEmpty() == false) {
            for (int i = 0; i < bodega_ingrediente.size() - 1; i++) {
                for (int j = 0; j < orden.peek().getLista_ingrediente().size(); j++) {
                    if (orden.peek().getLista_ingrediente().get(j).contentEquals(bodega_ingrediente.get(i).peek())) {
                        try {
                            bodega_ingrediente.get(i).pop();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, "No hay suficientes ingredintes en bodega!!!!");
                        }
                    }
                }
            }
            new Thread(new Hilo(orden.poll(), bodega_ingrediente, cocina3)).start();
        } else {
            JOptionPane.showMessageDialog(null, "No hay ni una orden");
        }
        c3.setSelected(false);
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
        if (orden.isEmpty() == false) {
            for (int i = 0; i < bodega_ingrediente.size() - 1; i++) {
                for (int j = 0; j < orden.peek().getLista_ingrediente().size(); j++) {
                    if (orden.peek().getLista_ingrediente().get(j).contentEquals(bodega_ingrediente.get(i).peek())) {
                        try {
                            bodega_ingrediente.get(i).pop();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, "No hay suficientes ingredintes en bodega!!!!");
                        }
                    }
                }
            }
            new Thread(new Hilo(orden.poll(), bodega_ingrediente, cocina4)).start();
        } else {
            JOptionPane.showMessageDialog(null, "No hay ni una orden");
        }
        c4.setSelected(false);
    }//GEN-LAST:event_c4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
        if (orden.isEmpty() == false) {
            for (int i = 0; i < bodega_ingrediente.size() - 1; i++) {
                for (int j = 0; j < orden.peek().getLista_ingrediente().size(); j++) {
                    if (orden.peek().getLista_ingrediente().get(j).contentEquals(bodega_ingrediente.get(i).peek())) {
                        try {
                            bodega_ingrediente.get(i).pop();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, "No hay suficientes ingredintes en bodega!!!!");
                        }
                    }
                }
            }
            new Thread(new Hilo(orden.poll(), bodega_ingrediente, cocina5)).start();
        } else {
            JOptionPane.showMessageDialog(null, "No hay ni una orden");
        }
        c5.setSelected(false);
    }//GEN-LAST:event_c5ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        Producto[] temp = new Producto[10];
        System.out.println(camiones);
        System.out.println(ventas);
        for (int j = 0; j < 10; j++) {
            if (j == ventas.size()) {
                break;
            } else {
                temp[j] = ventas.get(j);
            }
        }
        camiones.add(new Camion(temp));

        for (int i = 0; i < camiones.size(); i++) {

            camiones.get(i).imprime();
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        Reporte.setTitle("Reportes");
        Reporte.setVisible(true);
        Reporte.pack();
        int tiempo = 0;
        double precio = 0.0;
        for (int i = 0; i < ventas.size(); i++) {
            tiempo += ventas.get(i).getTiempo();
            precio += ventas.get(i).getPrecio();
        }
        txt_reporte.append("Reporte\n");
        txt_reporte.append("Bodega al inicio del dia\n");
        txt_reporte.append(bodega_reporte.toString() + "\n");
        txt_reporte.append("Bodega al final del dia\n");
        txt_reporte.append(bodega_ingrediente.toString() + "\n");
        txt_reporte.append("Ordenes realizadas\n");
        txt_reporte.append(ventas.toString() + "\n");
        txt_reporte.append("Tiempo Total en Cocina\n");
        txt_reporte.append(Integer.toString(tiempo) + "segundos" + "\n");
        txt_reporte.append("Precio Total de Ventas\n");
        txt_reporte.append("$." + Double.toString(precio) + "\n");


    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        grafo.addNodos(1);
        grafo.setNombreNodo(numero, ruta.getText());
        grafo.setPesoArista(numero, Integer.parseInt(peso.getText()));
        numero++;
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        int[] nodo = grafo.getNodos();
        for (int i = 0; i < nodo.length; i++) {
            model.addElement(grafo.getNombreNodo(i));
            model2.addElement(grafo.getNombreNodo(i));
        }
        inicio.setModel(model);
        end.setModel(model2);
        ruta.setText("");
        peso.setText("");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        grafo.addArista(inicio.getSelectedIndex(), end.getSelectedIndex(), true, grafo.getPesosAristas().getValue(inicio.getSelectedIndex()));
        //grafo.getfloyd();
        grafo.ver();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Camiones;
    private javax.swing.JFrame Cocina;
    private javax.swing.JFrame Envios;
    private javax.swing.JFrame Ingrediente;
    private javax.swing.JFrame Producto;
    private javax.swing.JFrame Reporte;
    private javax.swing.JFrame Rutas;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JSpinner cantidad;
    private javax.swing.JProgressBar cocina1;
    private javax.swing.JProgressBar cocina2;
    private javax.swing.JProgressBar cocina3;
    private javax.swing.JProgressBar cocina4;
    private javax.swing.JProgressBar cocina5;
    private javax.swing.JComboBox eli_produ;
    private javax.swing.JSpinner eliminar;
    private javax.swing.JComboBox end;
    private javax.swing.JComboBox ingrediente_cb;
    private javax.swing.JComboBox inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox lista_ingre;
    private javax.swing.JSpinner mod_cocina;
    private javax.swing.JComboBox mod_listaingre;
    private javax.swing.JSpinner mod_precio;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombre_produc;
    private javax.swing.JComboBox orde_producto;
    private javax.swing.JTextField peso;
    private javax.swing.JSpinner precio;
    private javax.swing.JComboBox producto;
    private javax.swing.JTextField ruta;
    private javax.swing.JSpinner tiempo;
    private javax.swing.JTextArea txt_reporte;
    // End of variables declaration//GEN-END:variables
ArrayList<Stack<String>> bodega_ingrediente = new ArrayList<Stack<String>>();
    ArrayList<Stack<String>> bodega_reporte = new ArrayList<Stack<String>>();
    ArrayList temp = new ArrayList();
    ArrayList<Producto> productos = new ArrayList<Producto>();
    Queue<Producto> orden = new LinkedList<Producto>();
    ArrayList<Producto> ventas = new ArrayList<Producto>();
    ArrayList<Camion> camiones = new ArrayList<Camion>();
    Grafo grafo = new Grafo();
    int numero = 1;
}
